name:                egregex
version:             0.1.0.0
github:              "gciruelos/egregex"
license:             MIT
author:              "Gonzalo Ciruelos"
maintainer:          "gonzalo.ciruelos@gmail.com"
copyright:           "2018 Gonzalo Ciruelos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gciruelos/egregex#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec == 3.1.13.0

library:
  source-dirs: src

executables:
  egregex:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - egregex

tests:
  egregex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egregex
